title: Jerome-Mathew's Portfolio
email: jeromemathew01@gmail.com
description: ""
author: "Jerome-Mathew Ngoh"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - stylish-portfolio-.gif

# Social Profiles
LinkedIn: "Jerome-Mathew Ngoh"
github_username: "jerome-mathew-devops"
